# Stock Exchange Data
This dataset consists of stock exchange data since 1965 for several indexes. It contains the daily stock prices along with the volume traded each day.

Not sure where to begin? Scroll to the bottom to find challenges!

In [2]:
import pandas as pd
stock = pd.read_csv("data\stock_data.csv", index_col=None)
print(stock.shape)
stock.head(100)

(104224, 9)

,Index,Date,Open,High,Low,Close,Adj Close,Volume,CloseUSD
0,HSI,1986-12-31,2568.300049,2568.300049,2568.300049,2568.300049,2568.300049,0.0,333.879006
1,HSI,1987-01-02,2540.100098,2540.100098,2540.100098,2540.100098,2540.100098,0.0,330.213013
2,HSI,1987-01-05,2552.399902,2552.399902,2552.399902,2552.399902,2552.399902,0.0,331.811987
3,HSI,1987-01-06,2583.899902,2583.899902,2583.899902,2583.899902,2583.899902,0.0,335.906987
4,HSI,1987-01-07,2607.100098,2607.100098,2607.100098,2607.100098,2607.100098,0.0,338.923013
...,...,...,...,...,...,...,...,...,...
95,HSI,1987-05-21,2871.000000,2871.000000,2871.000000,2871.000000,2871.000000,0.0,373.230000
96,HSI,1987-05-22,2897.600098,2897.600098,2897.600098,2897.600098,2897.600098,0.0,376.688013
97,HSI,1987-05-25,2897.600098,2897.600098,2897.600098,2897.600098,2897.600098,0.0,376.688013
98,HSI,1987-05-26,2935.899902,2935.899902,2935.899902,2935.899902,2935.899902,0.0,381.666987
99,HSI,1987-05-27,2941.600098,2941.600098,2941.600098,2941.600098,2941.600098,0.0,382.408013

## Data Dictionary
| Column            | Explanation                                                                                             |
| ----------------- | ------------------------------------------------------------------------------------------------------- |
| Index             | Ticker symbol for indexes
| Date              | Data of observation
| Open              | Opening price
| High              | Highest price during trading day
| Low               | Lowest price during trading day
| Close             | Close price
| Adj Close         | Close price adjusted for stock splits and dividends
| Volume            | Number of shares traded during trading day
| CloseUSD          | Close price in terms of USD

[Source](https://www.kaggle.com/mattiuzc/stock-exchange-data) of dataset.

## Don't know where to start?

**Challenges are brief tasks designed to help you practice specific skills:**

- üó∫Ô∏è **Explore**: Which index has produced the highest average annual return?
- üìä **Visualize**: Create a plot visualizing a 30 day moving average for an index of your choosing.
- üîé **Analyze**: Compare the volatilities of the indexes included in the dataset.

**Scenarios are broader questions to help you develop an end-to-end project for your portfolio:**

You are working for an investment firm that is looking to invest in index funds. They have provided you with a dataset containing the returns of 13 different indexes. Your manager has asked you to make short-term forecasts for several of the most promising indexes to help them decide which would be a good fund to include. Your analysis should also include a discussion of the associated risks and volatility of each fund you focus on.

You will need to prepare a report that is accessible to a broad audience. It should outline your motivation, steps, findings, and conclusions.